version: "3.7"

volumes:
  app:

services:
  # API
  app:
    restart: always
    container_name: app
    command: bash /init-apache.sh
    image: tipomrsk/rastreio.com-apache:latest
    ports:
      - 9000:80
    depends_on:
      mysql:
        condition: service_healthy
  # MySQL
  mysql:
    image: mysql
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cpfsearch
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10