version: "3.7"

volumes:
  app:

services:
  app:
    image: app
    restart: always
    container_name: app
    working_dir: /var/www/html
    command: bash ./init.sh
    hostname: app
    build:
      context: ../app
      dockerfile: Dockerfile
    volumes:
      - ../app:/var/www/html
    ports:
      - 80:80
    depends_on:
      mysql:
        condition: service_healthy

  # MySQL
  mysql:
    image: mysql
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dicelink.io
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10